version: 1

wallet:
  name: wallet2
pool:
  name: local
agent:
  port: 3210
modules:
  static:
    helloWorld: 
      path: /Users/saholman/Documents/oit/dev/apps/indy-agent/modules/helloWorld.py
      message_types:
      - test
      permissions:
      - /
  active: # Not yet implemented
    ui:
      port: 3000
      message_types:
      - test
      permissions:
      - /
